/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.pa.jlife105718;

public class Cellula {
    private Stato stato;
    public Cellula(Stato stato){
        this.stato=stato;
    }

    public Stato getStato() {
        return stato;
    }

    private void setStato(Stato stato) {
        this.stato = stato;
    }

    public void changeStato(){
        if(stato == Stato.VIVO)
            setStato(Stato.MORTO);
        else setStato(Stato.VIVO);
    }
    public boolean isAlive(){
        if(this.getStato()==Stato.VIVO)
            return true;
        else return false;
    }


}
