/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.pa.jlife105718;

import java.util.ArrayList;
import java.util.List;

public class Cellula {
    private List<PropertyListener> listeners;
    private Stato stato;
    public Cellula(Stato stato){
        this.stato=stato;
        listeners= new ArrayList<>();
    }

    public Stato getStato() {
        return stato;
    }

    private void setStato(Stato stato) {
        this.stato = stato;
    }

    public void changeStato(){
        if(stato == Stato.VIVO)
            setStato(Stato.MORTO);
        else setStato(Stato.VIVO);
        publishPropertyEvent("cellula.state",getStato());
    }
    public boolean isAlive(){
        if(this.getStato()==Stato.VIVO)
            return true;
        else return false;
    }
    public void addPropertyListener (PropertyListener lis){
        listeners.add(lis);
    }
    private void publishPropertyEvent(String name, Stato state){
        this.listeners.forEach(prop->prop.onPropertyEvent(this,name,state));
    }
}
