/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.pa.jlife105718;

import it.unicam.cs.pa.jlife105718.Model.Cell.MyCell;
import it.unicam.cs.pa.jlife105718.Model.Cell.Stato;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class CellulaTest {
    private MyCell cellula;

    @BeforeEach
    void createCellula(){
        cellula = new MyCell(Stato.MORTO,0);
    }

    @Test
    void testChangeStato() {
        cellula.changeStato();
        assertSame(cellula.getStato(), Stato.VIVO);
        cellula.changeStato();
        assertSame(cellula.getStato(), Stato.MORTO);
    }

    @Test
    void testIsAlive(){
        cellula.changeStato();
        assertTrue(cellula.isAlive());
        cellula.changeStato();
        assertFalse(cellula.isAlive());
    }


}

