/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.pa.jlife105718.Model.CellTest;

import it.unicam.cs.pa.jlife105718.Model.Cell.MyCell;
import it.unicam.cs.pa.jlife105718.Model.Cell.Stato;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class MyCellTest {
    private MyCell cellula1;
    private MyCell cellula2;

    @BeforeEach
    void createCellula(){
        cellula1 = new MyCell(Stato.MORTO,0);
        cellula2 = new MyCell(Stato.MORTO, 1);
    }

    @Test
    void testChangeStato() {
        cellula1.changeStato();
        assertSame(cellula1.getStato(), Stato.VIVO);
        cellula1.changeStato();
        assertSame(cellula1.getStato(), Stato.MORTO);
    }

    @Test
    void testIsAlive(){
        cellula1.changeStato();
        assertTrue(cellula1.isAlive());
        cellula1.changeStato();
        assertFalse(cellula1.isAlive());
    }

    @Test
    void testEquals(){
        MyCell tmpCell = cellula2;
        assertNotEquals(cellula2, cellula1);
        assertEquals(cellula2,tmpCell);
        cellula2.changeStato();
        assertEquals(cellula2,tmpCell);
    }

    @Test
    void testHashCode(){
        assertNotEquals(cellula2.getId(),cellula1.getId());
        MyCell tmpCell = cellula2;
        assertEquals(tmpCell.getId(), cellula2.getId());
        assertEquals(tmpCell,cellula2);
    }
}

